### ISSUE TITLE
Missing xmlparser

### ISSUE THREAD

**Issue by JasonIamAUnixAdmin** [sensu-plugins/sensu-plugins-supervisor#15]
After installing the plugin using the plugin mgr  I am getting this error:
`[root@XXXX bin]# /opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-supervisor-socket.rb -s /tmp/supervisor.sock
Check failed to run: cannot load such file -- xmlparser, ["/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/opt/sensu/embedded/lib/ruby/2.3.0/xmlrpc/parser.rb:608:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-supervisor-1.0.0/bin/check-supervisor-socket.rb:93:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-supervisor-1.0.0/bin/check-supervisor-sock`

tried adding this gem:  libxml-xmlrpc no change to the error output. 

Is there an expected OS pkg missing? Is the plugin not listing a dependency?

**Comment by hany** [comment]
I had this same issue. To resolve I had to install both the `expat-devel` system package (for a CentOS system), and install the gem `xmlparser` using the embedded `gem`:

```
# /opt/sensu/embedded/bin/gem install xmlparser
Building native extensions.  This could take a while...
Successfully installed xmlparser-0.7.2.1
Parsing documentation for xmlparser-0.7.2.1
Installing ri documentation for xmlparser-0.7.2.1
Done installing documentation for xmlparser after 5 seconds
1 gem installed
```

```
/opt/sensu/embedded/bin/check-supervisor-socket.rb -s /var/tmp/supervisor.sock
CheckSupervisorSocket OK: All processes running
```

**Comment by majormoses** [comment]
@hany could you put together a pr to document the package installation and an update to the gemspec for the required gem?

**Comment by hany** [comment]
@majormoses check out https://github.com/sensu-plugins/sensu-plugins-supervisor/pull/18

Let me know if this works for you.

**Comment by majormoses** [comment]
@hany looks good just some minor changelog stuff and we can call this good.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-supervisor/versions/1.0.2
