### ISSUE TITLE
XMLParser issue after Sensu 0.29 upgrade and embedded ruby 2.4.0

### ISSUE THREAD

**Issue by imusmanmalik** [sensu-plugins/sensu-plugins-supervisor#16]
Hi Guys,

I upgraded today sensu omnibus package to 0.29 and it upgraded ruby gems 2.4.0.

Error:

```
> /opt/sensu/embedded/bin/check-supervisor-socket.rb -s /tmp/supervisord.sock
> CheckSupervisorSocket CRITICAL: Tried requesting XMLRPC 'supervisor.getAllProcessInfo' from UNIX domain socket /tmp/supervisord.sock but failed: uninitialized constant XMLRPC::XMLParser::XMLStreamParser
> Did you mean?  XMLRPC::XMLParser::LibXMLStreamParser
```

Fix:

Edit: /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-supervisor-1.0.0/bin/check-supervisor-socket.rb

Change Line 93 which is

`success, result = XMLRPC::XMLParser::XMLStreamParser.new.parseMethodResponse(response.body)`

to

`success, result = XMLRPC::XMLParser::LibXMLStreamParser.new.parseMethodResponse(response.body)`

It works as expected then. Sorry didn't had the time to open pull request for this.

**Comment by majormoses** [comment]
closed via: https://github.com/sensu-plugins/sensu-plugins-supervisor/issues/17
